export type ComponentName = 'BAGTAG_PRINTER' | 'BAGTAG_FEEDER' | 'BAGTAG_DISPENSER' | 'BOARDINGPASS_PRINTER' | 'BOARDINGPASS_FEEDER' | 'BOARDINGPASS_DISPENSER' | 'PASSPORT_READER' | 'BARCODE_READER' | 'GENERAL_PURPOSE_PRINTER' | 'GENERAL_PURPOSE_FEEDER' | 'GENERAL_PURPOSE_DISPENSER' | 'ILIMINATION' | 'ADA_PAD' | 'ANNOUNCESMENT' | 'DISPLAY' | 'PAYMENT' | 'CONVEYOR' | 'BIOMETRIC';

export const ComponentName = {
  BAGTAG_PRINTER: 'BAGTAG_PRINTER' as ComponentName,
  BAGTAG_FEEDER: 'BAGTAG_FEEDER' as ComponentName,
  BAGTAG_DISPENSER: 'BAGTAG_DISPENSER' as ComponentName,
  BOARDINGPASS_PRINTER: 'BOARDINGPASS_PRINTER' as ComponentName,
    OUTOFSEQUENCE: 'OUT_OF_SEQUENCE' as ComponentName,
    TIMEOUT: 'TIMEOUT' as ComponentName,
    SESSIONTIMEOUT: 'SESSION_TIMEOUT' as ComponentName
     }