/**
 * Common Use Self Service V2 API Definition
 * <h3>Definiton of the new CUSS2 API.</h3>This API definition idescribes IATA Common Use Self Service (IATA RP 1706c), a standard that allows multiple airlines to share physical kiosks or other hardware devices to offer self-services to their passengers. These services include, but are not limited to passenger check-in functionality and self-service baggage drop off. The standard also defines how airlines and other application suppliers can develop CUSS-compliant applications that are able to run on any device whose platform is CUSS-compliant.<br><br>The API definiton is accompanied by the CUSS Specification (CUSS-TS), describing in human readable form (textual and graphical) the concepts, requirements, interaction, workflows and behavior for both CUSS platforms and CUSS applications, and the CUSS Implementation Guide (CUSS-IG) describing best practices and giving examples on how to implement CUSS compliant platforms- and applications.<br><br>The API requires and includes further schema definitions/domains as<br><br>- CUSS2 Basic Schemas<br>- CUSS2 Self Bag Drop<br>- CUSS2 Biometrics<br>- CUSS2 Payments<br>- CUSS2 Illumination<br><br>The IATA Common Use Group (CUG) and the CUSS Technical Solution Group (CUSS-TSG) maintain this API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorizationAmounts } from './authorizationAmounts';
import { EPaymentMessageTransactionTransactionRequestAccount } from './ePaymentMessageTransactionTransactionRequestAccount';
import { EPaymentMessageTransactionTransactionRequestEnvironment } from './ePaymentMessageTransactionTransactionRequestEnvironment';
import { EPaymentMessageTransactionTransactionRequestItinerary } from './ePaymentMessageTransactionTransactionRequestItinerary';
import { EPaymentMessageTransactionTransactionRequestPreAuth } from './ePaymentMessageTransactionTransactionRequestPreAuth';
import { GPParameterList } from './gPParameterList';

/**
 * Financial request from common use application to payment component.
 */
export interface EPaymentMessageTransactionTransactionRequest { 
    language?: string;
    environment?: EPaymentMessageTransactionTransactionRequestEnvironment;
    preAuth?: EPaymentMessageTransactionTransactionRequestPreAuth;
    account?: EPaymentMessageTransactionTransactionRequestAccount;
    itinerary?: EPaymentMessageTransactionTransactionRequestItinerary;
    /**
     * Descriptive billing information. This optional value lets the CUSS application suggest a value that will appear on the kiosk application user’s payment summary (monthly bill, etc.) as an extended description of the transaction. The value may or may not appear on the customer’s bill depending on the capabilities of the airport and customer’s banking systems. Long data may be truncated.  The platform may also be used as an additional tracking mechanism for other systems such as aggregator and reconciliation infrastructure.
     */
    billingDescription?: string;
    gpParameters?: GPParameterList;
    authorizationAmounts?: AuthorizationAmounts;
}