/**
 * Common Use Self Service V2 API Definition
 * <h3>Definiton of the new CUSS2 API.</h3>This API definition idescribes IATA Common Use Self Service (IATA RP 1706c), a standard that allows multiple airlines to share physical kiosks or other hardware devices to offer self-services to their passengers. These services include, but are not limited to passenger check-in functionality and self-service baggage drop off. The standard also defines how airlines and other application suppliers can develop CUSS-compliant applications that are able to run on any device whose platform is CUSS-compliant.<br><br>The API definiton is accompanied by the CUSS Specification (CUSS-TS), describing in human readable form (textual and graphical) the concepts, requirements, interaction, workflows and behavior for both CUSS platforms and CUSS applications, and the CUSS Implementation Guide (CUSS-IG) describing best practices and giving examples on how to implement CUSS compliant platforms- and applications.<br><br>The API requires and includes further schema definitions/domains as<br><br>- CUSS2 Basic Schemas<br>- CUSS2 Self Bag Drop<br>- CUSS2 Biometrics<br>- CUSS2 Payments<br>- CUSS2 Illumination<br><br>The IATA Common Use Group (CUG) and the CUSS Technical Solution Group (CUSS-TSG) maintain this API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OperationDocumentType } from './operationDocumentType';

/**
 * Request that the component perform some function that is not a direct financial transaction, such as key management, start-of-day, end-of-day, cashier sign-on, system status check, etc.
 */
export interface EPaymentMessageOperation { 
    operationDocumentType: OperationDocumentType;
    operationDocumentReturnType?: OperationDocumentType;
    operationType: EPaymentMessageOperation.OperationTypeEnum;
    /**
     * Some requests may require additional qualifying data, but those that do not are not required to explicitly include this element.
     */
    operationRequest?: string;
    operationResponse?: EPaymentMessageOperation.OperationResponseEnum;
}
export namespace EPaymentMessageOperation {
    export type OperationTypeEnum = 'system-health';
    export const OperationTypeEnum = {
        Health: 'system-health' as OperationTypeEnum
    };
    export type OperationResponseEnum = 'offline' | 'online';
    export const OperationResponseEnum = {
        Offline: 'offline' as OperationResponseEnum,
        Online: 'online' as OperationResponseEnum
    };
}