/**
 * Common Use Self Service V2 API Definition
 * <h3>Definiton of the new CUSS2 API.</h3>This API definition idescribes IATA Common Use Self Service (IATA RP 1706c), a standard that allows multiple airlines to share physical kiosks or other hardware devices to offer self-services to their passengers. These services include, but are not limited to passenger check-in functionality and self-service baggage drop off. The standard also defines how airlines and other application suppliers can develop CUSS-compliant applications that are able to run on any device whose platform is CUSS-compliant.<br><br>The API definiton is accompanied by the CUSS Specification (CUSS-TS), describing in human readable form (textual and graphical) the concepts, requirements, interaction, workflows and behavior for both CUSS platforms and CUSS applications, and the CUSS Implementation Guide (CUSS-IG) describing best practices and giving examples on how to implement CUSS compliant platforms- and applications.<br><br>The API requires and includes further schema definitions/domains as<br><br>- CUSS2 Basic Schemas<br>- CUSS2 Self Bag Drop<br>- CUSS2 Biometrics<br>- CUSS2 Payments<br>- CUSS2 Illumination<br><br>The IATA Common Use Group (CUG) and the CUSS Technical Solution Group (CUSS-TSG) maintain this API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApprovalCode } from './approvalCode';
import { AuthorizationAmounts } from './authorizationAmounts';
import { GPParameterList } from './gPParameterList';
import { MediaType } from './mediaType';
import { ReceiptData } from './receiptData';
import { TransactionReference } from './transactionReference';

/**
 * Approval reference information. An application may use this information as it chooses. No sensitive payment information shall be provided in this element. Various data items, such as cryptogram, may be required by some application providers for proper payment processing and reconciliation.
 */
export interface EPaymentMessageTransactionTransactionResponseApproval { 
    cardholderReceiptPrinted?: boolean;
    merchantReceiptPrinted?: boolean;
    transactionReference?: TransactionReference;
    mediaType?: MediaType;
    /**
     * Type of approval.
     */
    approvalType?: EPaymentMessageTransactionTransactionResponseApproval.ApprovalTypeEnum;
    /**
     * For an approval that requires subsequent signature verification by the application, and where the component has electronic signature capture capability, the signature capture (PNG format) data in base64 representation.
     */
    signatureCapture?: string;
    /**
     * Card brand name.
     */
    cardBrand?: string;
    /**
     * Secured (masked or truncated) card primary account number.
     */
    cardPAN?: string;
    approvalCode?: ApprovalCode;
    gpParameters?: GPParameterList;
    authorizationAmounts: AuthorizationAmounts;
    receiptData?: Array<ReceiptData>;
}
export namespace EPaymentMessageTransactionTransactionResponseApproval {
    export type ApprovalTypeEnum = 'none' | 'pin' | 'signature';
    export const ApprovalTypeEnum = {
        None: 'none' as ApprovalTypeEnum,
        Pin: 'pin' as ApprovalTypeEnum,
        Signature: 'signature' as ApprovalTypeEnum
    };
}