/**
 * Common Use Self Service V2 API Definition
 * <h3>Definiton of the new CUSS2 API.</h3>This API definition idescribes IATA Common Use Self Service (IATA RP 1706c), a standard that allows multiple airlines to share physical kiosks or other hardware devices to offer self-services to their passengers. These services include, but are not limited to passenger check-in functionality and self-service baggage drop off. The standard also defines how airlines and other application suppliers can develop CUSS-compliant applications that are able to run on any device whose platform is CUSS-compliant.<br><br>The API definiton is accompanied by the CUSS Specification (CUSS-TS), describing in human readable form (textual and graphical) the concepts, requirements, interaction, workflows and behavior for both CUSS platforms and CUSS applications, and the CUSS Implementation Guide (CUSS-IG) describing best practices and giving examples on how to implement CUSS compliant platforms- and applications.<br><br>The API requires and includes further schema definitions/domains as<br><br>- CUSS2 Basic Schemas<br>- CUSS2 Self Bag Drop<br>- CUSS2 Biometrics<br>- CUSS2 Payments<br>- CUSS2 Illumination<br><br>The IATA Common Use Group (CUG) and the CUSS Technical Solution Group (CUSS-TSG) maintain this API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Airline/merchant identifier where operating in a multi-merchant environment. If not supplied, the component is expected or required to determine it. The merchant ID in the CUSS schema is not the same technical value as the merchant ID used by the Payment Service Provider. In CUSS, this optional value lets a CUSS application provide an indicator about which company or provider is to receive the funds for the transaction.<br><br>- The CUSS application provider will need to indicate the list of valid merchant IDs that an application may request at time of payment.<br>- The CUSS platform will likely do an internal mapping of application request values, to values suitable for the platform’s payment solution.<br>- The CUSS platform will likely validate and filter the merchant-id in transaction requests from the CUSS application.<br>- If no value is specified, the platform will use an appropriate value (as set up during initial deployment of payment capabilities) for the transaction based on the companyCode value of the CUSS application making the transaction request.<br>- This field is most likely to be used within applications that process transactions for multiple entities, such as ground handling or generic airport applications.
 */
export type MerchantID = string;